name: promptflow-executor-e2e-test
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  executor_e2e_tests:
    runs-on: ubuntu-latest
    steps:
    - name: test
      shell: pwsh
      if ("aaabbb" -eq "${{ secrets.MY_SECRET }}") {`
        exit 1 `
      }
