name: promptflow-env-trigger
on: pull_request
permissions:
  id-token: write
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    environment: external
    steps:
      - uses: actions/checkout@v3
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SHARED_DEVOPS_IDENTITY }}
