name: promptflow-env-trigger
on: 
  pull_request_target:
    paths:
      - '**blank.yml'
      - 'README.md'
permissions:
  id-token: write
  contents: read
jobs:
  authorize:
    environment:
      ${{ github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository &&
      'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: true

  test:
    needs: authorize
    runs-on: ubuntu-latest
    environment: external
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      - name: Sending PR status to checkenforcer
        run: |-
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -f state='success' \
            -f target_url='https://github.com/microsoft/promptflow/actions/runs/${{ github.run_id }}' \
            -f description='The build succeeded!' \
            -f context='test/sdk_cli'
        shell: bash -el {0}
        env:
          GITHUB_TOKEN: ${{ github.token }}
