name: new_blank
on: 
  push:
    
jobs:
  job-name:  # set your job name to something nice.
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Change blank.yml
        run: |
          echo " " >> ${{github.workspace}}/.github/workflows/blank.yml
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: apply auto commit
