name: promptflow-sdk-cli-test
on: 
  pull_request:
    branches: main
permissions:
  id-token: write
  contents: read

jobs:
  job-name:  # set your job name to something nice.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # all branches and tags
      - name: Set git identity
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Change blank.yml
        run: |
          echo " " >> ${{github.workspace}}/.github/workflows/blank.yml
      - name: Push
        run: |
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}
          git push
