name: new_blank
on: 
  pull_request:
    branches: main
permissions:
  contents: write

jobs:
  job-name:  # set your job name to something nice.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Change blank.yml
        run: |
          echo " " >> ${{github.workspace}}/.github/workflows/blank.yml
      - uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: actions@github.com
