name: promptflow-pr
on: 
  pull_request:
    paths:
      - '**pr.yml'
      - 'README.md'
permissions:
  id-token: write
  contents: read
jobs:
  authorize:
    runs-on: ubuntu-latest
    steps:
      - run: true

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      - name: Sending PR status to checkenforcer
        run: |-
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -f state='success' \
            -f target_url='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}' \
            -f description='The build succeeded!' \
            -f context='test/sdk_cli'
        shell: bash -el {0}
        env:
          GITHUB_TOKEN: ${{ github.token }}
